add logging option

diff --git a/cloudbuild.yml b/cloudbuild.yml
--- a/cloudbuild.yml
+++ b/cloudbuild.yml
@@ -4,6 +4,7 @@ steps:
     args:
       - '-c'
       - |
+        set -e  # Exit immediately if a command exits with a non-zero status
         export NEXT_PUBLIC_SUPABASE_URL=$(gcloud secrets versions access latest --secret="NEXT_PUBLIC_SUPABASE_URL")
         export NEXT_PUBLIC_SUPABASE_ANON_KEY=$(gcloud secrets versions access latest --secret="NEXT_PUBLIC_SUPABASE_ANON_KEY")
         export STRIPE_PUBLIC_KEY=$(gcloud secrets versions access latest --secret="STRIPE_PUBLIC_KEY")
@@ -11,15 +12,17 @@ steps:
         export STRIPE_SECRET_KEY=$(gcloud secrets versions access latest --secret="STRIPE_SECRET_KEY")
         export RESEND_API_KEY=$(gcloud secrets versions access latest --secret="RESEND_API_KEY")
         export NEXT_PUBLIC_RESEND_API_KEY=$(gcloud secrets versions access latest --secret="NEXT_PUBLIC_RESEND_API_KEY")
+
         docker build \
-          --build-arg NEXT_PUBLIC_SUPABASE_URL=$NEXT_PUBLIC_SUPABASE_URL \
-          --build-arg NEXT_PUBLIC_SUPABASE_ANON_KEY=$NEXT_PUBLIC_SUPABASE_ANON_KEY \
-          --build-arg STRIPE_PUBLIC_KEY=$STRIPE_PUBLIC_KEY \
-          --build-arg NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=$NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY \
-          --build-arg STRIPE_SECRET_KEY=$STRIPE_SECRET_KEY \
-          --build-arg RESEND_API_KEY=$RESEND_API_KEY \
-          --build-arg NEXT_PUBLIC_RESEND_API_KEY=$NEXT_PUBLIC_RESEND_API_KEY \
-          -t gcr.io/$PROJECT_ID/my-nextjs-app:$COMMIT_SHA .
+          --build-arg NEXT_PUBLIC_SUPABASE_URL="$NEXT_PUBLIC_SUPABASE_URL" \
+          --build-arg NEXT_PUBLIC_SUPABASE_ANON_KEY="$NEXT_PUBLIC_SUPABASE_ANON_KEY" \
+          --build-arg STRIPE_PUBLIC_KEY="$STRIPE_PUBLIC_KEY" \
+          --build-arg NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY="$NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY" \
+          --build-arg STRIPE_SECRET_KEY="$STRIPE_SECRET_KEY" \
+          --build-arg RESEND_API_KEY="$RESEND_API_KEY" \
+          --build-arg NEXT_PUBLIC_RESEND_API_KEY="$NEXT_PUBLIC_RESEND_API_KEY" \
+          -t gcr.io/$PROJECT_ID/prairie-books:$COMMIT_SHA .
+
   - name: 'gcr.io/cloud-builders/docker'
     args:
       - push
@@ -27,3 +30,5 @@ steps:
 
 images:
   - 'gcr.io/$PROJECT_ID/prairie-books:$COMMIT_SHA'
+
+logging: 'CLOUD_LOGGING_ONLY '
